name: Cherry Pick

on:
  workflow_dispatch:
    inputs:
      commit_hash:
        description: 'Commit hash to cherry pick'
        required: true
        default: ''
      target_repo_url:
        description: 'Target repository URL'
        required: true
        default: 'https://github.com/target-repo.git'
      target_branch:
        description: 'Target branch to cherry pick from'
        required: true
        default: 'main'
      review_branch:
        description: 'Name of the new review branch'
        required: true
        default: ''

jobs:
  cherry-pick:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout your branch
      uses: actions/checkout@v4.2.2
      with:
        ref: main

    - name: Debug information
      run: |
        echo "Commit hash: ${{ github.event.inputs.commit_hash }}"
        echo "Target repo URL: ${{ github.event.inputs.target_repo_url }}"
        echo "Target branch: ${{ github.event.inputs.target_branch }}"
        echo "Review branch: ${{ github.event.inputs.review_branch }}"

    - name: Checkout target repository
      uses: actions/checkout@v4.2.2
      with:
        repository: ${{ github.event.inputs.target_repo_url }}
        ref: ${{ github.event.inputs.target_branch }}
        path: target-repo

    - name: Create new review branch
      run: |
        cd target-repo
        git checkout -b ${{ github.event.inputs.review_branch }}
        git cherry-pick ${{ github.event.inputs.commit_hash }}
        git push origin ${{ github.event.inputs.review_branch }}
